apiVersion: v1
kind: Service
metadata:
  name: campus-beats-frontend
spec:
  selector:
    app: campus-beats-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
